version: 2

jobs:
  linux:
    docker:
      - image: codevapor/swift:5.2
    steps:
      - checkout
      - run: swift build
      - run: swift test
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
